### ISSUE TITLE
Improvement: Add QR Code to Github Auth Window

### ISSUE THREAD

**Issue by arcsur** [drinfernoo/plugin.program.opendevtools#1]
Add a QR code for the URL to perform GH auth to make it easier for users to access the authorization link

**Comment by drinfernoo** [comment]
While I like this idea, there's only one real way to do it, which is to create a custom dialog... and while that's not outside of the realm of possibility, my complaint against custom windows is that it's often very difficult to get one that works exactly right in every skin.

I'll look into how generic I can get with it and see how it looks across skins.
