### ISSUE TITLE
*bug* Commit time  is not properly localized

### ISSUE THREAD

**Issue by SerpentDrago** [drinfernoo/plugin.program.opendevtools#2]
![image](https://user-images.githubusercontent.com/21133858/120359462-b1199b00-c2d5-11eb-9d53-12ff9659b12d.png)
![image](https://user-images.githubusercontent.com/21133858/120359515-c098e400-c2d5-11eb-9295-28acdea91166.png)
![image](https://user-images.githubusercontent.com/21133858/120359539-c68ec500-c2d5-11eb-8470-a3ff50c1ee75.png)

All pictures taken within a few mins of each other

**Comment by drinfernoo** [comment]
Oh yeah... I knew about this but need to properly account for time zones for it to be totally accurate.

**Comment by drinfernoo** [comment]
Can you test 206f231 (or latest, either one should be fine) from the `tz` branch?

**Comment by SerpentDrago** [comment]
fixed in tz branch 

![image](https://user-images.githubusercontent.com/21133858/120384690-7b37df00-c2f4-11eb-936a-98b282ab3072.png)

works great
